
name: Go
permissions:
  actions: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Testing on bash
        run: ls .

      - name: Coverage report
        uses: eleboys/test-coverage-report-action@v1.0.2
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: Karma Test Coverage
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Testing on bash
        run: ls .
      - name: Update status to pending
        uses: geekodour/gh-actions-custom-status@v0.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LAST_COMMIT_SHA: ${{ github.event.client_payload.LAST_COMMIT_SHA }}
        with:
          args: >-
            --state=pending
            --context=foo-status-update
            --target_url=https://github.com/${{ github.repository }}/actions

