
name: Go
permissions:
  actions: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Testing on bash
        run: ls .
        with:
          name: Test Basic Success (Implicit)
          conclusion: success
          output: |
            {"summary":"50%","text_description":"50%"}
