
name: Go
permissions:
  actions: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Testing on bash
        run: ls .

      - name: Coverage report
        uses: eleboys/test-coverage-report-action@v1.0.2
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: Karma Test Coverage
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Testing on bash
        run: ls .
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        ignorefork: false
        token: ${{ secrets.GITHUB_TOKEN }}

